{{- $general := $.Values.alertsGeneral -}}
{{- range $name, $alert := .Values.alerts }}
{{- if ne (.enabled | toString) "false" }}
{{- $merged := mergeOverwrite dict $general . }}
{{- with $merged }}
---
apiVersion: {{ .apiVersion | default "monitoring.coreos.com/v1" }}
kind: PrometheusRule
{{ include "obj.metadata" (dict "name" (.name | default $name) "value" . "context" $) }}
spec:
  {{- . | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
{{- end -}}
