{{- range $name, $sm := .Values.serviceMonitors }}
{{- if ne (.enabled | toString) "false" }}
{{- $merged := deepCopy $.Values.serviceMonitorsGeneral  | mergeOverwrite . }}
{{- with $merged }}
---
apiVersion: {{ .apiVersion | default "monitoring.coreos.com/v1" }}
kind: ServiceMonitor
{{ include "obj.metadata" (dict "name" $name "value" . "context" $) }}
spec:
  endpoints:
    {{- include "helpers.tpl" (dict "value" .endpoints "context" $) | nindent 4 }}
  selector:
    matchLabels:
      {{- include "helpers.obj.selectorLabels" (dict "value" . "context" $) | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
