{{- $general := $.Values.gatewaysGeneral -}}
{{- range $name, $gateway := .Values.gateways }}
{{- if ne (.enabled | toString) "false" }}
{{- $merged := mergeOverwrite dict $general . }}
{{- with $merged }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
{{ include "obj.metadata" (dict "name" $name "value" . "context" $) }}
spec:
  {{- with .gatewayClassName }}gatewayClassName: {{ . }}{{- end }}
  listeners:
    {{- range .listeners }}
    {{- include "helpers.tpl" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
