{{- range $name, $hpa := .Values.hpas }}
{{- if ne (.enabled | toString) "false" }}
---
apiVersion: {{ include "common.capabilities.hpa.apiVersion" $ }}
kind: HorizontalPodAutoscaler
{{ include "obj.metadata" (dict "name" $name "value" . "context" $) }}
spec:
  {{- include "helpers.hpa.target" (dict "name" $name "scaleTargetRef" .scaleTargetRef "context" $) | nindent 2 }}
  minReplicas: {{ .minReplicas | default 2 }}
  maxReplicas: {{ .maxReplicas | default 3 }}
  metrics:
    {{- with .targetCPU }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ . }}
    {{- end }}
    {{- with .targetMemory }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ . }}
    {{- end }}
    {{- with .metrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
{{- end -}}
