{{- range $name, $secret := .Values.secrets -}}
{{- if ne (.enabled | toString) "false" }}
{{- if not (eq $name "envs") }}
---
apiVersion: v1
kind: Secret
type: {{ $secret.type | default  "Opaque" }}
{{ include "obj.metadata" (dict "name" $name "value" . "context" $) }}
data:
  {{- include "helpers.secrets.render" (dict "value" $secret.data) | indent 2 }}
{{- end }}
{{- end }}
{{- end }}

{{- if or (not (empty .Values.secretEnvs)) (not (empty .Values.secretEnvsString)) }}
---
apiVersion: v1
kind: Secret
type: Opaque
{{ include "obj.metadata" (dict "name" "envs" "value" . "context" $) }}
data:
  {{- include "helpers.secrets.render" (dict "value" .Values.secretEnvsString) | indent 2 }}
  {{- include "helpers.secrets.render" (dict "value" .Values.secretEnvs) | indent 2 }}
{{- end }}

{{- range $name, $value := .Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
{{ include "obj.metadata" (dict "name" $name "value" . "context" $) }}
data:
  {{- include "helpers.secrets.render" (dict "value" (printf ".dockerconfigjson: %v" $value)) | indent 2 }}
{{- end }}
