ingresses:
  my-ingress-name:
    serviceName: 8080
    servicePort: 8080
    hosts:
      - hostname: my.example.com
        paths:
          - path: /abc
          - path: /foo
          - path: /bar


services:
  8080:
    enabled: true
