{{- if .Values.deployments }}
{{- $general := $.Values.deploymentsGeneral -}}
{{- /* Fix: int=0 */ -}}
{{- range $key, $val := $general }}
    {{- if kindIs "float64" $val }}
    {{- $_ := set $general $key ($val | toString) -}}
    {{- end -}}
{{- end -}}

{{- range $name, $d := .Values.deployments }}
{{- if ne (.enabled | toString) "false" }}

{{- /* Fix: int=0 */ -}}
{{- range $key, $val := $d }}
    {{- if kindIs "float64" $val -}}
    {{- $_ := set $d $key ($val | toString) -}}
    {{- end -}}
{{- end -}}


{{- $merged := mergeOverwrite dict $general . }}
{{- with $merged }}
---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" $ }}
kind: Deployment
{{ include "obj.metadata" (dict "name" $name "value" . "context" $) }}
spec:
  {{- with .replicas }}
  replicas: {{ . }}
  {{- end }}
  {{- with .minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with .progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with .strategy }}
  strategy: {{- include "helpers.tpl" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helpers.obj.selectorLabels" (dict "value" . "context" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helpers.obj.selectorLabels" (dict "value" . "context" $) | nindent 8 }}
        {{- with $.Values.podLabels }}{{- include "helpers.tpl" (dict "value" . "context" $) | nindent 8 }}{{- end }}
        {{- with .podLabels }}{{- include "helpers.tpl" (dict "value" . "context" $) | nindent 8 }}{{- end }}
      annotations:
        {{- include "helpers.workloads.checksum" $ | nindent 8 }}
        {{- with $.Values.podAnnotations }}{{- include "helpers.tpl" (dict "value" . "context" $) | nindent 8 }}{{- end }}
        {{- with .podAnnotations }}{{- include "helpers.tpl" (dict "value" . "context" $) | nindent 8 }}{{- end }}
    spec:
      {{- include "helpers.pod" (dict "value" . "name" $name "context" $) | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
