{{- range $name, $i := .Values.namespaces }}
{{- if ne (.enabled | toString) "false" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" ( $name | default .name) "context" $) }}
  labels:
    {{- include "helpers.obj.labels" (dict "value" . "context" $) | nindent 4 }}
  {{- if any $.Values.annotations .annotations }}
  annotations:
    {{- with $.Values.annotations }}{{- include "helpers.tpl" (dict "value" . "context" $) | nindent 4 }}{{- end }}
    {{- with .annotations }}{{- include "helpers.tpl" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  {{- end }}
{{- end -}}
{{- end -}}
