{{- $general := $.Values.pdbsGeneral -}}
{{- range $name, $pdb := .Values.pdbs }}
{{- if ne (.enabled | toString) "false" }}
{{- $merged := mergeOverwrite dict $general . }}
{{- with $merged }}
---
apiVersion: {{ include "common.capabilities.pdb.apiVersion" $ }}
kind: PodDisruptionBudget
{{ include "obj.metadata" (dict "name" $name "value" . "context" $) }}
spec:
  {{- if any .minAvailable .maxUnavailable}}
  {{- with .minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  {{- else }}
  {{- $error := printf "minAvailable or maxUnavailable must be defined at $.Values.pdbs.%s" $name }}
  {{- fail $error }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helpers.obj.selectorLabels" (dict "value" . "context" $) | nindent 6 }}
{{- end -}}
{{- end -}}
{{- end -}}
