{{- $general := $.Values.argocdAppSetsGeneral -}}
{{- range $name, $a := .Values.argocdAppSets }}
{{- if ne (.enabled | toString) "false" }}
{{- $merged := mergeOverwrite dict $general . }}
{{- with $merged }}
---
apiVersion: {{ .apiVersion | default "argoproj.io/v1alpha1" }}
kind: ApplicationSet
{{ include "obj.metadata" (dict "name" (.name | default $name) "value" . "context" $) }}
spec:
  # TODO: would u extend here?
  {{- include "helpers.tpl" (dict "value" . "context" $) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
