name: CI

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '[0-9]+.[0-9]+.[0-9]+'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Push
      uses: appany/helm-oci-chart-releaser@v0.3.0
      with:
        name: uni # chart name
        repository: zhilyaev/uni-chart
        tag: ${{ env.GIT_TAG }}
        path: .
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ github.token }}
    
